<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <AssemblyName>BatteryHelper.Service</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BatteryHelper.Sensors\BatteryHelper.Sensors.csproj" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.0" />
  </ItemGroup>
</Project>
